### ISSUE TITLE
SABER not working with recent keras/tensorflow versions

### ISSUE THREAD

**Issue by DmitryMalishev** [BaderLab/Saber#196]
While trying to launch test sample of SABER locally or using provided Google Notebook ("saber_lightning_tour.ipynb") I get the following error:

**AttributeError: module 'tensorflow' has no attribute 'placeholder'**

It's raises on _model = model_from_json(f.read(), custom_objects={'CRF': CRF})_

Tensorflow 2.0+ versions do not support placeholders, but since it's loaded through keras there is no options but to use old 1.X versions on tensorflow, which require to reinstall half of python's modules.

Could you please take a look?

**Comment by JohnGiorgi** [comment]
Hey @DmitryMalishev,

Saber is no longer being maintained. If you need it to reproduce a score from our paper let me know and I can dig into this problem (or just report the score directly). Otherwise, I would look elsewhere for IE tools for biomed (like [Stanzy](https://stanfordnlp.github.io/stanza/biomed.html)). Thanks!
